export const FETCH_USERINFO_START = 'FETCH_USERINFO_START';
export const FETCH_USERINFO_SUCCESS = 'FETCH_USERINFO_SUCCESS';
export const FETCH_USERINFO_FAIL = 'FETCH_USERINFO_FAIL';

export const FETCH_CREDICT_START = 'FETCH_CREDICT_START';
export const FETCH_CREDICT_SUCCESS = 'FETCH_CREDICT_SUCCESS';
export const FETCH_CREDICT_FAIL = 'FETCH_CREDICT_FAIL';
